"""
Django settings for wechat_admin project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-_!c6$-qdsqr=gcm#^a=ro1t9fg!#woncdh_9471^txn$=x(@zx')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# 允许的主机名
ALLOWED_HOSTS = ['*', '.vercel.app']

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'import_export',
    'dashboard',
    'users',
    'vip',
    'carousel',
    'question_bank',
    'api',
    'rest_framework_simplejwt',  # 添加JWT依赖
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wechat_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wechat_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 跨域设置
CORS_ALLOW_ALL_ORIGINS = DEBUG  # 开发环境允许所有域名
if not DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "https://your-frontend-domain.com",  # 替换为你的前端域名
    ]
CORS_ALLOW_CREDENTIALS = True

# 安全设置
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 微信小程序配置
WECHAT_MINI_APP = {
    'APP_ID': os.getenv('WX_APP_ID', 'wx4da605ed0f30f980'),
    'APP_SECRET': os.getenv('WX_APP_SECRET', '96454fcd2ab2897d4ce9f5b647db0db4')
}

# SimpleUI 配置
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['用户管理', 'VIP管理', '轮播图管理', '题库管理', '数据统计', '认证和授权'],
    'dynamic': True,
    'menus': [
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '用户列表',
                    'icon': 'fas fa-user',
                    'url': 'users/user/'
                }
            ]
        },
        {
            'name': 'VIP管理',
            'icon': 'fas fa-crown',
            'models': [
                {
                    'name': 'VIP套餐',
                    'url': 'vip/vippackage/',
                    'icon': 'fas fa-box'
                },
                {
                    'name': 'VIP订阅记录',
                    'url': 'vip/vipsubscription/',
                    'icon': 'fas fa-receipt'
                }
            ]
        },
        {
            'name': '轮播图管理',
            'icon': 'fas fa-images',
            'models': [
                {
                    'name': '轮播图列表',
                    'url': 'carousel/carousel/',
                    'icon': 'far fa-image'
                }
            ]
        },
        {
            'name': '题库管理',
            'icon': 'fas fa-book',
            'models': [
                {
                    'name': '题目分类',
                    'url': 'question_bank/category/',
                    'icon': 'fas fa-folder'
                },
                {
                    'name': '题目管理',
                    'url': 'question_bank/question/',
                    'icon': 'fas fa-question-circle'
                },
                {
                    'name': '答题记录',
                    'url': 'question_bank/useranswer/',
                    'icon': 'fas fa-history'
                }
            ]
        },
        {
            'name': '数据统计',
            'icon': 'fas fa-chart-line',
            'models': [
                {
                    'name': '每日统计',
                    'url': 'dashboard/dailystats/',
                    'icon': 'fas fa-chart-bar'
                }
            ]
        }
    ]
}

# SimpleUI 设置
SIMPLEUI_HOME_INFO = False  # 关闭首页信息
SIMPLEUI_ANALYSIS = False   # 关闭使用分析
SIMPLEUI_STATIC_OFFLINE = True  # 使用离线模式
SIMPLEUI_LOGO = 'https://your-logo-url.com/logo.png'  # 设置你的Logo
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'  # 设置默认主题
SIMPLEUI_ICON = {
    '用户管理': 'fas fa-users',
    'VIP管理': 'fas fa-crown',
    '轮播图管理': 'fas fa-images',
    '题库管理': 'fas fa-book',
    '数据统计': 'fas fa-chart-line',
}

# REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# JWT设置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 自定义用户模型
AUTH_USER_MODEL = 'users.User'
